plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.ulak'
    compileSdk 35

    defaultConfig {
        applicationId "com.ulak"
        minSdk 24
        targetSdk 35
        versionCode 8
        versionName "1.0.5"
        
        resConfigs "tr"
    }

    signingConfigs {
        release {
            storeFile file("../key/ulak-key.jks")
            storePassword "Fatih2807(html!)"
            keyAlias "ulak_key"
            keyPassword "Fatih2807(html!)"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
    
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'
    implementation 'androidx.activity:activity-ktx:1.8.2'
    
    // Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    
    // Encryption
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'
    
    // Jsoup for HTML parsing
    implementation 'org.jsoup:jsoup:1.17.2'
}
